### ISSUE TITLE
Error(when do ./experiments/examples/VGG_CNN_S/test_vgg_s_rap.sh)

### ISSUE THREAD

**Issue by jhj7905** [kyu-sz/WPAL-network#10]
@kyu-sz 
Hello 
I have a problem when i run the ./experiments/examples/VGG_CNN_S/test_vgg_s_rap.sh
The message is like below

I0926 13:07:32.307726  6862 net.cpp:165] Memory required for data: 40234208
I0926 13:07:32.307734  6862 net.cpp:228] score does not need backward computation.
I0926 13:07:32.307744  6862 net.cpp:228] heat5 does not need backward computation.
I0926 13:07:32.307752  6862 net.cpp:228] heat4 does not need backward computation.
I0926 13:07:32.307760  6862 net.cpp:228] heat3 does not need backward computation.
I0926 13:07:32.307767  6862 net.cpp:228] pred does not need backward computation.
I0926 13:07:32.307775  6862 net.cpp:228] fc_syn2 does not need backward computation.
I0926 13:07:32.307783  6862 net.cpp:228] fc_syn1 does not need backward computation.
I0926 13:07:32.307791  6862 net.cpp:228] concat does not need backward computation.
I0926 13:07:32.307799  6862 net.cpp:228] relu5_e does not need backward computation.
I0926 13:07:32.307807  6862 net.cpp:228] fc5_e does not need backward computation.
I0926 13:07:32.307816  6862 net.cpp:228] relu4_e does not need backward computation.
I0926 13:07:32.307823  6862 net.cpp:228] fc4_e does not need backward computation.
I0926 13:07:32.307832  6862 net.cpp:228] relu3_e does not need backward computation.
I0926 13:07:32.307838  6862 net.cpp:228] fc3_e does not need backward computation.
I0926 13:07:32.307847  6862 net.cpp:228] pool5_e_pool5_e_0_split does not need backward computation.
I0926 13:07:32.307855  6862 net.cpp:228] pool5_e does not need backward computation.
I0926 13:07:32.307863  6862 net.cpp:228] pool4_e_pool4_e_0_split does not need backward computation.
I0926 13:07:32.307871  6862 net.cpp:228] pool4_e does not need backward computation.
I0926 13:07:32.307879  6862 net.cpp:228] pool3_e_pool3_e_0_split does not need backward computation.
I0926 13:07:32.307886  6862 net.cpp:228] pool3_e does not need backward computation.
I0926 13:07:32.307895  6862 net.cpp:228] conv5_e_ReLU5_e_0_split does not need backward computation.
I0926 13:07:32.307904  6862 net.cpp:228] ReLU5_e does not need backward computation.
I0926 13:07:32.307911  6862 net.cpp:228] conv5_e does not need backward computation.
I0926 13:07:32.307919  6862 net.cpp:228] conv4_e_ReLU4_e_0_split does not need backward computation.
I0926 13:07:32.307927  6862 net.cpp:228] ReLU4_e does not need backward computation.
I0926 13:07:32.307934  6862 net.cpp:228] conv4_e does not need backward computation.
I0926 13:07:32.307942  6862 net.cpp:228] conv3_e_ReLU3_e_0_split does not need backward computation.
I0926 13:07:32.307962  6862 net.cpp:228] ReLU3_e does not need backward computation.
I0926 13:07:32.307971  6862 net.cpp:228] conv3_e does not need backward computation.
I0926 13:07:32.307977  6862 net.cpp:228] ReLU5 does not need backward computation.
I0926 13:07:32.307986  6862 net.cpp:228] conv5 does not need backward computation.
I0926 13:07:32.307992  6862 net.cpp:228] conv4_ReLU4_0_split does not need backward computation.
I0926 13:07:32.308001  6862 net.cpp:228] ReLU4 does not need backward computation.
I0926 13:07:32.308007  6862 net.cpp:228] conv4 does not need backward computation.
I0926 13:07:32.308015  6862 net.cpp:228] conv3_ReLU3_0_split does not need backward computation.
I0926 13:07:32.308022  6862 net.cpp:228] ReLU3 does not need backward computation.
I0926 13:07:32.308029  6862 net.cpp:228] conv3 does not need backward computation.
I0926 13:07:32.308037  6862 net.cpp:228] pool2 does not need backward computation.
I0926 13:07:32.308044  6862 net.cpp:228] ReLU2 does not need backward computation.
I0926 13:07:32.308063  6862 net.cpp:228] conv2 does not need backward computation.
I0926 13:07:32.308071  6862 net.cpp:228] pool1 does not need backward computation.
I0926 13:07:32.308079  6862 net.cpp:228] norm1 does not need backward computation.
I0926 13:07:32.308087  6862 net.cpp:228] ReLU1 does not need backward computation.
I0926 13:07:32.308094  6862 net.cpp:228] conv1 does not need backward computation.
I0926 13:07:32.308102  6862 net.cpp:228] input does not need backward computation.
I0926 13:07:32.308109  6862 net.cpp:270] This network produces output heat3
I0926 13:07:32.308130  6862 net.cpp:270] This network produces output heat4
I0926 13:07:32.308138  6862 net.cpp:270] This network produces output heat5
I0926 13:07:32.308146  6862 net.cpp:270] This network produces output pred
I0926 13:07:32.308153  6862 net.cpp:270] This network produces output score
I0926 13:07:32.308185  6862 net.cpp:283] Network initialization done.
I0926 13:07:32.461284  6862 net.cpp:761] Ignoring source layer input-data
I0926 13:07:32.474005  6862 net.cpp:761] Ignoring source layer drop3_p
I0926 13:07:32.474040  6862 net.cpp:761] Ignoring source layer drop4_p
I0926 13:07:32.474048  6862 net.cpp:761] Ignoring source layer drop5_p
I0926 13:07:32.474269  6862 net.cpp:761] Ignoring source layer drop3
I0926 13:07:32.474503  6862 net.cpp:761] Ignoring source layer drop4
I0926 13:07:32.475388  6862 net.cpp:761] Ignoring source layer drop5
I0926 13:07:32.478900  6862 net.cpp:761] Ignoring source layer drop
I0926 13:07:32.479084  6862 net.cpp:761] Ignoring source layer loss
./experiments/examples/VGG_CNN_S/test_vgg_s_rap_inference.sh: line 3:  6862 Segmentation fault      (core dumped) ./tools/test_net_inference.py --setid 0 --net ./data/snapshots/VGG_S_MLL_RAP/0/RAP/vgg_s_mll_rap_iter_10000.caffemodel --def ./models/VGG_S_MLL_RAP/test_net.prototxt --gpu 1 --db RAP

I think it is related to the memory of gpu.
is it right? if it is right then can you tell me how to solve this problem..

**Comment by kyu-sz** [comment]
I am not sure, but FYI, I used Titan X with 12GB of GPU memory to train this model.
