### ISSUE TITLE
I could not download the RAP dataset,could you please share the dataset by other ways

### ISSUE THREAD

**Issue by gittigxuy** [kyu-sz/WPAL-network#11]
I live in China,you know because of some reasons,I could not download the RAP dataset.I could not open the link:   rap.idealtest.org,so could you please share the dataset by other ways?Thank you

**Comment by kyu-sz** [comment]
Sorry but I do not own the dataset. Please contact Dangwei Li (dangwei.li@nlpr.ia.ac.cn).
