### ISSUE TITLE
Training:Did someone have a experience that the error values was lowered down to 10?

### ISSUE THREAD

**Issue by jhj7905** [kyu-sz/WPAL-network#13]
Hello

After I downloaded the RAP dataset and VGG_S model, i ran the script as below
./data/scripts/fetch_pretrained_vgg_cnn_s_model.sh
./experiments/example/VGG_CNN_S/train_vgg_s_rap_0.sh

but you mentioned before in https://github.com/kyu-sz/WPAL-network/issues/2
"Two days are enough for the loss to drop to around 10 or 5...

but i did not get the same result(Error value was aprroximately 15). 
My setting is same as train_vgg_s_rap_0.sh. i did not modify the script.
so i have a question
Did someone have a experience that the error values was lowered down to 10?

thank you in advance

**Comment by kyu-sz** [comment]
The final loss does depend on luck... Sorry for not providing the random seed for reproduction.
And I highly recommend you to refer the latest version of this project at [Yang Zhou's repository](https://github.com/YangZhou1994/WPAL-network). There are several improvements, and I believe the results are better.

**Comment by kclch** [comment]
@jhj7905 Hello, I am also studying this project recently. Have you trained the model?
