### ISSUE TITLE
你好，能提供训练好的模型吗?

### ISSUE THREAD

**Issue by zg9uagfv** [kyu-sz/WPAL-network#14]
RAP数据集的维护者没有回复邮件，拿不到数据集，无法训练。
1.你能提供已经训练好的模型吗？
2.用PETA database怎么训练？

非常感谢

**Comment by kyu-sz** [comment]
不好意思，我这里没有保留训练好的模型。PETA数据集需要预处理成跟RAP数据集一样的格式才能直接套现成的代码，否则需要对读取数据库的代码进行修改。
