### ISSUE TITLE
how to reduce the number of attribute

### ISSUE THREAD

**Issue by jhj7905** [kyu-sz/WPAL-network#16]
Hello, @kyu-sz 
I have confirmed the your algorithm these days.
I wanna reduce the number of attribute(ex.. 92 -> 13)
Then, what are some parts the i need to modify?
Can you tell me?
i think i modify the config.py and .mat file

**Comment by kyu-sz** [comment]
I think you can just search for the keyword "92" in all files, and create copies of those files with those "92" modified to "13".

**Comment by kclch** [comment]
@jhj7905 Have you achieved a reduction in attributes?
