### ISSUE TITLE
the problem of CPU train

### ISSUE THREAD

**Issue by kclch** [kyu-sz/WPAL-network#28]
I use the cpu to train the model, and run the script "./experiments/examples/VGG_CNN_S/train_vgg_s_rap_cpu.sh" instead of "./experiments/examples/VGG_CNN_S/train_vgg_s_rap_0.sh".
then appear the problem"./experiments/scripts/wpal_net.sh: Line 39: 19548 killed. /tools/train_net.py --gpu ${GPU_ID} --solver models/${NET}/solver.prototxt --weights $ {WEIGHTS} --db ${DB} --setid ${DB_SET} --outputdir data/snapshots/${NET}/${DB_SET} --iters ${ITERS} ${EXTRA_ARGS}" This is due to computer configuration Question?

**Comment by kyu-sz** [comment]
I definitely suggest not to use CPU to train the model. It is really inefficient, and takes incredible time, and brings problems that we deep learning engineers hardly meet. Please consider using a GPU, and I would recommend Titan X or AWS.
