### ISSUE TITLE
Is there FSPP layer?

### ISSUE THREAD

**Issue by Hyena-** [kyu-sz/WPAL-network#6]
你好，代码中没有发现FSSP的网络结构，只有global pooling的 和 SPP层的，FSSP是不是要把两个网络结构合并啊？

**Comment by kyu-sz** [comment]
The FSPP is modified from the SPP layer in the Caffe snapshot specified by the submodule. You may find that there are some parameters in our SPP layer that are additional to the original SPP parameter set.
